export const TOGGLE_NEW_NOTE_DIALOG = "dialogs.TOGGLE_NEW_NOTE_DIALOG";
export const OPEN_NEW_NOTE_DIALOG = "dialogs.OPEN_NEW_NOTE_DIALOG";
export const CLOSE_NEW_NOTE_DIALOG = "dialogs.CLOSE_NEW_NOTE_DIALOG";
export const OPEN_EDIT_NOTE_DIALOG = "dialogs.OPEN_EDIT_NOTE_DIALOG";

export const TOGGLE_SETTINGS_DIALOG = "dialogs.TOGGLE_SETTINGS_DIALOG";
export const TOGGLE_ABOUT_DIALOG = "dialogs.TOGGLE_ABOUT_DIALOG";
